apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: shamsmo0h/service-c:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: service-c-svc
spec:
  selector:
    app: service-c
  ports:
  - port: 80
    targetPort: 8083
  type: ClusterIP